### ISSUE TITLE
图片不能显示

### ISSUE THREAD

**Issue by Axun** [yaodong/pentitugua-rss#1]
现在喷嚏网的图片有检测referer，导致RSS订阅的内容只要有图片都不能显示，有办法解决吗。

**Comment by yaodong** [comment]
@Axun 如果你使用的加密链接，就可以显示图片了。

**Comment by yaodong** [comment]
@Axun 请提交一个不能显示的图片的网址。

**Comment by yaodong** [comment]
下一个版本中，所有图片会被缓存。
