### ISSUE TITLE
xml比正常的晚一天?

### ISSUE THREAD

**Issue by uniquepengpeng** [yaodong/pentitugua-rss#4]
你好,
        rss源(http://www.pentitugua.com/rss.xml),不知道从什么开始,最新的都要比当前晚一天才能收的到.

**Comment by yaodong** [comment]
@uniquepengpeng 可能官方对列表页的输出做了延时。

**Comment by uniquepengpeng** [comment]
@yaodong 官方图挂专门的列表页是很早做了延时.但是我记得你这rss不是通过官方首页右侧解析的嘛(那个目测没延时),我记错了?

**Comment by yaodong** [comment]
@uniquepengpeng commit log 显示 29 号的图卦是 committed 5 hours ago。我本地 build 是可以看到的。但是 Github Pages 却没有。虽然很不合常理，但是我猜测是因为 build 时间过长，导致 Github Pages 将这个 repo 的 build 优先级排序降低。

**Comment by yaodong** [comment]
经过测试，确实是 jekyll build 时间太长导致的。已经改为只输出 RSS，去掉了 jekyll。
